TattooShop/Controllers/TiposTrabajoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TattooShop.Models;

namespace TattooShop.Controllers
{
    [Authorize]
    public class TiposTrabajoController : Controller
    {
        private Entities db = new Entities();

        // GET: TiposTrabajo
        public async Task<ActionResult> Index()
        {
            return View(await db.TipoTrabajo.ToListAsync());
        }

        // GET: TiposTrabajo/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoTrabajo tipoTrabajo = await db.TipoTrabajo.FindAsync(id);
            if (tipoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(tipoTrabajo);
        }

        // GET: TiposTrabajo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TiposTrabajo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Tipo")] TipoTrabajo tipoTrabajo)
        {
            if (ModelState.IsValid)
            {
                db.TipoTrabajo.Add(tipoTrabajo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(tipoTrabajo);
        }

        // GET: TiposTrabajo/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoTrabajo tipoTrabajo = await db.TipoTrabajo.FindAsync(id);
            if (tipoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(tipoTrabajo);
        }

        // POST: TiposTrabajo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,Tipo")] TipoTrabajo tipoTrabajo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoTrabajo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tipoTrabajo);
        }

        // GET: TiposTrabajo/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoTrabajo tipoTrabajo = await db.TipoTrabajo.FindAsync(id);
            if (tipoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(tipoTrabajo);
        }

        // POST: TiposTrabajo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TipoTrabajo tipoTrabajo = await db.TipoTrabajo.FindAsync(id);
            db.TipoTrabajo.Remove(tipoTrabajo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TattooShop/Views/TiposTrabajo/Create.cshtml
@model TattooShop.Models.TipoTrabajo

@{
    ViewBag.Title = "Crear Tipo Trabajo";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Tipos Trabajo</a></li>
        <li class="breadcrumb-item active">Nuevo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Crear nuevo
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "TiposTrabajo", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/TiposTrabajo/Delete.cshtml
@model TattooShop.Models.TipoTrabajo

@{
    ViewBag.Title = "Eliminar Tipo Trabajo";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Tipo Trabajo</a></li>
        <li class="breadcrumb-item active">Eliminar</li>
    </ol>
}

<div class="alert alert-danger alert-rounded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h4 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <b>Advertencia!</b> Está a punto de eliminar este elemento.</h4>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Eliminar
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tipo)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <button type="submit" class="btn btn-danger"><i class="ti-eraser"></i> Eliminar permanentemente</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

TattooShop/Views/TiposTrabajo/Details.cshtml
@model TattooShop.Models.TipoTrabajo

@{
    ViewBag.Title = "Detalles Tipo Trabajo";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Tipos Trabajo</a></li>
        <li class="breadcrumb-item active">Detalles</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Detalles
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tipo)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>

TattooShop/Views/TiposTrabajo/Edit.cshtml
@model TattooShop.Models.TipoTrabajo

@{
    ViewBag.Title = "Editar Tipo Trabajo";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Tipos Trabajo</a></li>
        <li class="breadcrumb-item active">Editar</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Editar
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "TiposTrabajo", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/TiposTrabajo/Index.cshtml
@model IEnumerable<TattooShop.Models.TipoTrabajo>

@{
    ViewBag.Title = "Listado Tipos Trabajo";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item active">Tipos Trabajo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Listado
                <div class="card-actions">
                    <a href="@Url.Action("Create")"><i class="ti-plus"></i> Agregar</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Tipo)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Tipo)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", new { id = item.id })"><i class="ti-pencil"></i></a> &ensp;
                                    <a href="@Url.Action("Details", new { id = item.id })"><i class="ti-eye"></i></a> &ensp;
                                    <a href="@Url.Action("Delete", new { id = item.id })"><i class="ti-eraser"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>