TattooShop/Models/Cita.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public double deposito { get; set; }

        [Display(Name = "Cliente")]
        public Nullable<int> cliente_id { get; set; }

        [Display(Name = "Tipo de Trabajo")]
        public Nullable<int> tipo_trabajo_id { get; set; }

        [Display(Name = "Artista")]
        public Nullable<int> artista_id { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual TipoTrabajo TipoTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}

TattooShop/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TattooShop.Models;

namespace TattooShop.Controllers
{
    [Authorize]
    public class CitasController : Controller
    {
        private Entities db = new Entities();

        // GET: Citas
        public async Task<ActionResult> Index()
        {
            var cita = db.Cita.Include(c => c.Artista).Include(c => c.Cliente).Include(c => c.TipoTrabajo);
            return View(await cita.ToListAsync());
        }

        // GET: Citas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = await db.Cita.FindAsync(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // GET: Citas/Create
        public ActionResult Create()
        {
            ViewBag.artista_id = new SelectList(db.Artista, "id", "nombre");
            ViewBag.cliente_id = new SelectList(db.Cliente, "id", "nombre");
            ViewBag.tipo_trabajo_id = new SelectList(db.TipoTrabajo, "id", "Tipo");
            return View();
        }

        // POST: Citas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,fecha,deposito,cliente_id,tipo_trabajo_id,artista_id")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                db.Cita.Add(cita);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.artista_id = new SelectList(db.Artista, "id", "nombre", cita.artista_id);
            ViewBag.cliente_id = new SelectList(db.Cliente, "id", "nombre", cita.cliente_id);
            ViewBag.tipo_trabajo_id = new SelectList(db.TipoTrabajo, "id", "Tipo", cita.tipo_trabajo_id);
            return View(cita);
        }

        // GET: Citas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = await db.Cita.FindAsync(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            ViewBag.artista_id = new SelectList(db.Artista, "id", "nombre", cita.artista_id);
            ViewBag.cliente_id = new SelectList(db.Cliente, "id", "nombre", cita.cliente_id);
            ViewBag.tipo_trabajo_id = new SelectList(db.TipoTrabajo, "id", "Tipo", cita.tipo_trabajo_id);
            return View(cita);
        }

        // POST: Citas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,fecha,deposito,cliente_id,tipo_trabajo_id,artista_id")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cita).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.artista_id = new SelectList(db.Artista, "id", "nombre", cita.artista_id);
            ViewBag.cliente_id = new SelectList(db.Cliente, "id", "nombre", cita.cliente_id);
            ViewBag.tipo_trabajo_id = new SelectList(db.TipoTrabajo, "id", "Tipo", cita.tipo_trabajo_id);
            return View(cita);
        }

        // GET: Citas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = await db.Cita.FindAsync(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cita cita = await db.Cita.FindAsync(id);
            db.Cita.Remove(cita);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TattooShop/Views/Citas/Create.cshtml
@model TattooShop.Models.Cita

@{
    ViewBag.Title = "Crear Cita";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Citas</a></li>
        <li class="breadcrumb-item active">Nuevo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Crear nueva
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "Citas", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", @placeholder = "DD/MM/YYYY HH:mm" } })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.deposito, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.deposito, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.deposito, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.cliente_id, "cliente_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("cliente_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.tipo_trabajo_id, "tipo_trabajo_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("tipo_trabajo_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.tipo_trabajo_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.artista_id, "artista_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("artista_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.artista_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link href="@Url.Content("~/Content/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css")" rel="stylesheet">
    <!-- Date picker plugins css -->
    <link href="@Url.Content("~/Content/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {

    <script src="@Url.Content("~/Content/plugins/moment/moment.js")"></script>
    <script src="@Url.Content("~/Content/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js")"></script>
    <script>
        // Date Picker
        $('#fecha').bootstrapMaterialDatePicker({
            format: 'DD/MM/YYYY HH:mm'
        });
    </script>

    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="@Url.Content("~/Content/plugins/styleswitcher/jQuery.style.switcher.js")"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Citas/Delete.cshtml
@model TattooShop.Models.Cita

@{
    ViewBag.Title = "Eliminar Cita";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Citas</a></li>
        <li class="breadcrumb-item active">Eliminar</li>
    </ol>
}

<div class="alert alert-danger alert-rounded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h4 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <b>Advertencia!</b> Está a punto de eliminar este elemento.</h4>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Eliminar
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.fecha)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.fecha)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.deposito)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.deposito)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Artista.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Artista.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Cliente.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cliente.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TipoTrabajo.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TipoTrabajo.Tipo)
                    </dd>

                </dl> @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <button type="submit" class="btn btn-danger"><i class="ti-eraser"></i> Eliminar permanentemente</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

TattooShop/Views/Citas/Details.cshtml
@model TattooShop.Models.Cita

@{
    ViewBag.Title = "Detalles Cita";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Citas</a></li>
        <li class="breadcrumb-item active">Detalles</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Detalles
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.fecha)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.fecha)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.deposito)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.deposito)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Artista.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Artista.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Cliente.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cliente.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TipoTrabajo.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TipoTrabajo.Tipo)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>

TattooShop/Views/Citas/Edit.cshtml
@model TattooShop.Models.Cita

@{
    ViewBag.Title = "Editar Cita";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Citas</a></li>
        <li class="breadcrumb-item active">Editar</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Editar
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "Artista", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.deposito, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.deposito, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.deposito, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.cliente_id, "cliente_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("cliente_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.tipo_trabajo_id, "tipo_trabajo_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("tipo_trabajo_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.tipo_trabajo_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.artista_id, "artista_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("artista_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.artista_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Citas/Index.cshtml
@model IEnumerable<TattooShop.Models.Cita>

@{
    ViewBag.Title = "Listado Citas";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item active">Citas</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Listado
                <div class="card-actions">
                    <a href="@Url.Action("Create")"><i class="ti-plus"></i> Agregar</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.fecha)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.deposito)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Artista.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cliente.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TipoTrabajo.Tipo)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.fecha)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.deposito)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Artista.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cliente.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TipoTrabajo.Tipo)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", new { id = item.id })"><i class="ti-pencil"></i></a> &ensp;
                                    <a href="@Url.Action("Details", new { id = item.id })"><i class="ti-eye"></i></a> &ensp;
                                    <a href="@Url.Action("Delete", new { id = item.id })"><i class="ti-eraser"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>