TattooShop/Models/Artista.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artista()
        {
            this.Cita = new HashSet<Cita>();
            this.Pago = new HashSet<Pago>();
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}

TattooShop/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TattooShop.Models;

namespace TattooShop.Controllers
{
    [Authorize]
    public class ArtistasController : Controller
    {
        private Entities db = new Entities();

        // GET: Artistas
        public async Task<ActionResult> Index()
        {
            return View(await db.Artista.ToListAsync());
        }

        // GET: Artistas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,nombre")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artista.Add(artista);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(artista);
        }

        // GET: Artistas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,nombre")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(artista);
        }

        // GET: Artistas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Artista artista = await db.Artista.FindAsync(id);
            db.Artista.Remove(artista);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TattooShop/Views/Artistas/Create.cshtml
@model TattooShop.Models.Artista

@{
    ViewBag.Title = "Crear Artista";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Artistas</a></li>
        <li class="breadcrumb-item active">Nuevo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Crear nuevo
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "Artista", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Artistas/Delete.cshtml
@model TattooShop.Models.Artista

@{
    ViewBag.Title = "Eliminar Artista";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Artistas</a></li>
        <li class="breadcrumb-item active">Eliminar</li>
    </ol>
}

<div class="alert alert-danger alert-rounded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h4 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <b>Advertencia!</b> Está a punto de eliminar este elemento.</h4>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Eliminar
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">               
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.nombre)
                    </dd>
                </dl>                

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <button type="submit" class="btn btn-danger"><i class="ti-eraser"></i> Eliminar permanentemente</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

TattooShop/Views/Artistas/Edit.cshtml
@model TattooShop.Models.Artista

@{
    ViewBag.Title = "Editar Artista";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Artistas")">Artistas</a></li>
        <li class="breadcrumb-item active">Editar</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Editar
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Edit", "Artista", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Artistas/Index.cshtml
@model IEnumerable<TattooShop.Models.Artista>

@{
    ViewBag.Title = "Listado Artistas";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item active">Artistas</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Listado
                <div class="card-actions">
                    <a href="@Url.Action("Create")"><i class="ti-plus"></i> Agregar</a>
                </div>
            </div>
            <div class="card-body">

                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.nombre)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nombre)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", new { id = item.id })"><i class="ti-pencil"></i></a> &ensp;
                                    <a href="@Url.Action("Details", new { id = item.id })"><i class="ti-eye"></i></a> &ensp;
                                    <a href="@Url.Action("Delete", new { id = item.id })"><i class="ti-eraser"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>