TattooShop/Models/Cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
    }
}

TattooShop/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TattooShop.Models;

namespace TattooShop.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private Entities db = new Entities();

        // GET: Clientes
        public async Task<ActionResult> Index()
        {
            return View(await db.Cliente.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,nombre,telefono")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,nombre,telefono")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cliente cliente = await db.Cliente.FindAsync(id);
            db.Cliente.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TattooShop/Views/Clientes/Create.cshtml
@model TattooShop.Models.Cliente

@{
    ViewBag.Title = "Crear Cliente";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Clientes</a></li>
        <li class="breadcrumb-item active">Nuevo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Crear nuevo
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Create", "Clientes", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Clientes/Delete.cshtml
@model TattooShop.Models.Cliente

@{
    ViewBag.Title = "Eliminar Cliente";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Clientes</a></li>
        <li class="breadcrumb-item active">Eliminar</li>
    </ol>
}

<div class="alert alert-danger alert-rounded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h4 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <b>Advertencia!</b> Está a punto de eliminar este elemento.</h4>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Eliminar
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.telefono)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.telefono)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <button type="submit" class="btn btn-danger"><i class="ti-eraser"></i> Eliminar permanentemente</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

TattooShop/Views/Clientes/Details.cshtml
@model TattooShop.Models.Cliente

@{
    ViewBag.Title = "Detalles Cliente";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Clientes</a></li>
        <li class="breadcrumb-item active">Detalles</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Detalles
                <div class="card-actions">
                    <a href="@Url.Action("Edit", new { id = Model.id })"><i class="ti-pencil"></i> Editar</a>
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.telefono)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.telefono)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>

TattooShop/Views/Clientes/Edit.cshtml
@model TattooShop.Models.Cliente

@{
    ViewBag.Title = "Editar Cliente";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index")">Clientes</a></li>
        <li class="breadcrumb-item active">Nuevo</li>
    </ol>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Crear nuevo
                <div class="card-actions">
                    <a href="@Url.Action("Index")"><i class="ti-arrow-left"></i> Volver</a>
                </div>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Create", "Clientes", FormMethod.Post, new { @class = "form-material", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TattooShop/Views/Clientes/Index.cshtml
@model IEnumerable<TattooShop.Models.Cliente>

@{
    ViewBag.Title = "Listado Clientes";
}

@section Breadcumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Inicio</a></li>
        <li class="breadcrumb-item active">Citas</li>
    </ol>
}

<div class="row el-element-overlay">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="el-card-item">
                    <div class="el-card-avatar el-overlay-1">
                        <img src="@Url.Content("~/Content/images/users/1.jpg")" alt="user" />
                        <div class="el-overlay">
                            <ul class="el-info">
                                <li><a class="btn default btn-outline" href="@Url.Action("Edit", new { id = item.id })"><i class="ti-pencil"></i></a></li>
                                <li><a class="btn default btn-outline" href="@Url.Action("Details", new { id = item.id })"><i class="ti-eye"></i></a></li>
                                <li><a class="btn default btn-outline" href="@Url.Action("Delete", new { id = item.id })"><i class="ti-eraser"></i></a></li>                            </ul>
                        </div>
                    </div>
                    <div class="el-card-content">
                        <h3 class="box-title">@Html.DisplayFor(modelItem => item.nombre)</h3> <small>@Html.DisplayFor(modelItem => item.telefono)</small>
                        <br />
                    </div>
                </div>
            </div>
        </div>        
    }
</div>